/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AnimalesVista;

import MenuPrincipal.MenuPrincipal;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import animales.AnimalesController;
import DAOanimales.DAOanimales;

/**
 *
 * @author Mateo Salcedo
 */
public class MostrarAnimal extends javax.swing.JFrame {

    private static MostrarAnimal instancia=null;
    private DefaultTableModel modelo;
    /**
     * Creates new form MostrarPokemon
     */
    private MostrarAnimal() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(this);
    }
    
    private void ActuListaAnimal(){
        DAOanimales anmCont = AnimalesController.getInstance();
        modelo=anmCont.MostrarAnimales();
        jTable2.setModel(modelo);
    }
    
    public static MostrarAnimal getInstance(){
        if(instancia==null)
            instancia=new MostrarAnimal();
        instancia.ActuListaAnimal();
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setBackground(new java.awt.Color(102, 102, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Animales registrados");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setBackground(new java.awt.Color(162, 155, 254));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton3.setBackground(new java.awt.Color(162, 155, 254));
        jButton3.setText("Agregar animal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton5.setBackground(new java.awt.Color(162, 155, 254));
        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton4.setBackground(new java.awt.Color(162, 155, 254));
        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton2.setBackground(new java.awt.Color(162, 155, 254));
        jButton2.setText("MostrarDatos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jTable2.setBackground(new java.awt.Color(116, 185, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.ActuListaAnimal();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AgregarAnimal interfaz = AgregarAnimal.getInstance();
        interfaz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menuprincipal = MenuPrincipal.getInstance();
        menuprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null,"["+jTable2.getSelectedRow()+","+jTable2.getSelectedColumn()+"]");
        try{
            if(jTable2.getSelectedRow()>=0){
                String seleccionTxt=""+modelo.getValueAt(jTable2.getSelectedRow(),jTable2.getSelectedColumn());
                if(!seleccionTxt.equals("null")){
                    //Arreglo de animal
                    String[] animal=new String[6];
                    for(int i=0;i<6;i++){
                        animal[i]=modelo.getValueAt(jTable2.getSelectedRow(),i).toString();
                    }
                    EditarAnimal editar = EditarAnimal.getInstance();
                    editar.setVisible(true);
                    editar.porDefecto();
                    editar.datosPorActualizar(animal);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null,"Debe seleccionar un campo no vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Debe seleccionar un elemento", "Advertencia", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try
       {
           AnimalesController animal= AnimalesController.getInstance();
            int codigo;
        
            codigo=jTable2.getSelectedRow();
            if(!String.valueOf(codigo).equals(null))
            {
                animal.EliminarAnimal(codigo);
            jTable2.setModel(animal.MostrarAnimales());
            }
            
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, "selecciona un elemento");
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
